version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - sam-local

networks:
  sam-local:
    name: sam-local
    driver: bridge